# -*- coding: utf-8 -*-
"""ChatBot_Tienda_De_Gatos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IGGTcr_bBcT-K_QIrcOvy9ya81ToTlp0

### 1. Instalación de dependencias y Configuración
Instalamos `onnx` y `onnxruntime` para la exportación posterior.
"""

!pip install onnx onnxruntime onnxscript

"""### 2. Creación del Dataset (Foco: Rascadores para Gatos)
Aquí definimos las intenciones (`tags`), los patrones de búsqueda (inputs del usuario) y las respuestas.
"""

import json
import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader

# Cargamos el nuevo archivo subido
with open('intents_tienda_gatos_v4_powerful.json', 'r', encoding='utf-8') as f:
    intents = json.load(f)

print(f'Dataset restaurado con {len(intents["intents"])} categorías y personalidad completa 🐱✨.')

"""### 3. Preprocesamiento de Lenguaje Natural (NLP)
Usaremos un tokenizador simple y convertiremos las palabras a una bolsa de palabras (Bag of Words) para que el modelo sea ligero.
"""

import nltk
from nltk.stem.porter import PorterStemmer
# Descargamos punkt y el nuevo recurso punkt_tab
nltk.download('punkt')
nltk.download('punkt_tab')
stemmer = PorterStemmer()

def tokenize(sentence):
    """Divide la frase en palabras/tokens"""
    return nltk.word_tokenize(sentence.lower())

def stem(word):
    """Reduce la palabra a su raíz"""
    return stemmer.stem(word.lower())

def bag_of_words(tokenized_sentence, words):
    sentence_words = [stem(word) for word in tokenized_sentence]
    bag = np.zeros(len(words), dtype=np.float32)
    for idx, w in enumerate(words):
        if w in sentence_words:
            bag[idx] = 1
    return bag

"""### 4. Preparación de los datos de entrenamiento
Extraemos todas las palabras y etiquetas para entrenar la red neuronal.
"""

all_words = []
tags = []
xy = []

for intent in intents['intents']:
    tag = intent['tag']
    tags.append(tag)
    for pattern in intent['patterns']:
        w = tokenize(pattern)
        all_words.extend(w)
        xy.append((w, tag))

ignore_words = ['?', '!', '.', ',']
all_words = [stem(w) for w in all_words if w not in ignore_words]
all_words = sorted(set(all_words))
tags = sorted(set(tags))

X_train = []
y_train = []

for (pattern_sentence, tag) in xy:
    bag = bag_of_words(pattern_sentence, all_words)
    X_train.append(bag)
    label = tags.index(tag)
    y_train.append(label)

X_train = np.array(X_train)
y_train = np.array(y_train)

print(f"¡Datos listos! Vocabulario: {len(all_words)} palabras.")

"""### 5. Definición del Modelo (Arquitectura de la Red)
Esta es una red neuronal lineal simple. Usamos `ReLU` como función de activación entre las capas para que el modelo aprenda relaciones no lineales.
"""

class NeuralNet(nn.Module):
    def __init__(self, input_size, hidden_size, num_classes):
        super(NeuralNet, self).__init__()
        # Primera capa: Entrada -> Oculta
        self.l1 = nn.Linear(input_size, hidden_size)
        # Segunda capa: Oculta -> Oculta
        self.l2 = nn.Linear(hidden_size, hidden_size)
        # Tercera capa: Oculta -> Salida (Tags)
        self.l3 = nn.Linear(hidden_size, num_classes)
        self.relu = nn.ReLU()
        self.dropout = nn.Dropout(0.2) # Evita que el modelo se memorice los patrones exactos

    def forward(self, x):
        out = self.l1(x)
        out = self.relu(out)
        out = self.dropout(out)
        out = self.l2(out)
        out = self.relu(out)
        out = self.dropout(out)
        out = self.l3(out)
        # No aplicamos Softmax aquí porque usaremos CrossEntropyLoss más adelante
        return out

"""### 6. Configuración y Entrenamiento
Aquí definimos los hiperparámetros como las **épocas** (cuántas veces el modelo verá todo el dataset) y el entrenamiento real.
"""

import torch

# --- Hiperparámetros y Configuración ---
num_epochs = 300
batch_size = 8
learning_rate = 0.001
input_size = len(X_train[0])
hidden_size = 16 # Punto medio para manejar 38 categorías
output_size = len(tags)

# Dataset y DataLoader
dataset = ChatDataset()
train_loader = DataLoader(dataset=dataset, batch_size=batch_size, shuffle=True)

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

# --- Lógica de Pesos de Clase (Para corregir generalización) ---
# Le damos un peso mayor (3.0) a 'gato_grande_pesado' para evitar confusiones con 'pagos'
weights = torch.ones(len(tags)).to(device)
try:
    target_idx = tags.index('gato_grande_pesado')
    weights[target_idx] = 3.0
    print(f"Reforzando peso para: '{tags[target_idx]}'")
except ValueError:
    pass

# Inicialización del Modelo
model = NeuralNet(input_size, hidden_size, output_size).to(device)
criterion = nn.CrossEntropyLoss(weight=weights)
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

# Historial para gráficas
loss_history = []
epoch_history = []

# --- Bucle de Entrenamiento ---
for epoch in range(num_epochs):
    for (words, labels) in train_loader:
        words = words.to(device)
        labels = labels.to(dtype=torch.long).to(device)

        outputs = model(words)
        loss = criterion(outputs, labels)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

    # Guardar métricas
    loss_history.append(loss.item())
    epoch_history.append(epoch + 1)

    if (epoch+1) % 50 == 0:
        print(f'Época [{epoch+1}/{num_epochs}], Pérdida: {loss.item():.6f}')

print(f'Entrenamiento finalizado con balance de pesos. El modelo ya debería ser más preciso.')

import matplotlib.pyplot as plt

# Generar la gráfica de entrenamiento
plt.figure(figsize=(10, 6))
plt.plot(epoch_history, loss_history, label='Pérdida (Loss)')
plt.title('Progreso del Entrenamiento del Chatbot')
plt.xlabel('Época')
plt.ylabel('Pérdida')
plt.legend()
plt.grid(True)
plt.show()

import matplotlib.pyplot as plt

# Visualización detallada de las últimas 100 épocas
plt.figure(figsize=(10, 5))
plt.plot(epoch_history, loss_history, color='orange', label='Curva de Pérdida')
plt.yscale('log') # Escala logarítmica para ver mejor los valores cercanos a cero
plt.title('Análisis de Convergencia (Escala Logarítmica)')
plt.xlabel('Época')
plt.ylabel('Pérdida (Log)')
plt.grid(True, which="both", ls="--")
plt.legend()
plt.show()

from sklearn.metrics import classification_report, accuracy_score

# 1. Realizar predicciones sobre el set de entrenamiento
model.eval()
with torch.no_grad():
    X_tensor = torch.from_numpy(X_train).to(device)
    outputs = model(X_tensor)
    _, predictions = torch.max(outputs, dim=1)
    y_pred = predictions.cpu().numpy()

# 2. Calcular métricas
accuracy = accuracy_score(y_train, y_pred)
report = classification_report(y_train, y_pred, target_names=tags)

print(f"--- Métricas del Modelo ---")
print(f"Precisión General (Accuracy): {accuracy:.4f}")
print("\nReporte Detallado por Categoría:")
print(report)

# Prueba de Generalización (Diagnóstico Actualizado)
test_phrases = [
    "hola que tal",
    "cuanto valen los rascadores",
    "tengo un michi muy gordo",
    "hacen envios a bogota"
]

print("--- Verificando Corrección de Generalización ---")
model.eval()
with torch.no_grad():
    for phrase in test_phrases:
        sentence = tokenize(phrase)
        X = bag_of_words(sentence, all_words)
        X = X.reshape(1, X.shape[0])
        X = torch.from_numpy(X).to(device)

        output = model(X)
        probs = torch.softmax(output, dim=1)
        prob, predicted = torch.max(probs, dim=1)
        tag = tags[predicted.item()]

        print(f"Frase: '{phrase}' -> Tag: {tag} (Confianza: {prob.item():.4f})")

"""### 7. Exportación a ONNX para despliegue Web
Este paso convierte el modelo de PyTorch a un formato universal legible por JavaScript.
"""

import torch.onnx
import json

# 1. Definir rutas
onnx_model_path = "chatbot_model_v1.5.onnx"
metadata_path = "metadata_v4.json"

# 2. Exportar el modelo a ONNX
# Aseguramos que el modelo esté en modo evaluación
model.eval()
dummy_input = torch.randn(1, input_size).to(device)

torch.onnx.export(
    model,
    dummy_input,
    onnx_model_path,
    export_params=True,
    opset_version=14,
    do_constant_folding=True,
    input_names=['input'],
    output_names=['output'],
    dynamic_axes={'input': {0: 'batch_size'}, 'output': {0: 'batch_size'}}
)

# 3. Guardar metadatos para JavaScript
# Estos datos son CRUCIALES para que tu JS sepa cómo codificar el texto del usuario
metadata = {
    "all_words": all_words,
    "tags": tags,
    "responses": {intent['tag']: intent['responses'] for intent in intents['intents']}
}

with open(metadata_path, "w", encoding='utf-8') as f:
    json.dump(metadata, f, ensure_ascii=False, indent=4)

print(f"¡Éxito total!")
print(f"1. Descarga '{onnx_model_path}' para tu modelo.")
print(f"2. Descarga '{metadata_path}' para la lógica de respuestas en JS.")

"""### 🚀 Prompt para Implementación en Antigravity

Copia y pega el siguiente texto en tu herramienta de IA:

---

**Contexto:** Estoy desarrollando un Chatbot para una tienda de rascadores de gatos. He entrenado un modelo en PyTorch y lo he exportado a formato ONNX. Necesito una implementación en **JavaScript/Node.js** que se ejecute localmente.

**Ubicación de archivos:**
Los archivos necesarios están en: `C:\Proyectos\Tia\ejemplos`
1. `chatbot_model_V1.2.onnx` (Modelo)
2. `metadata.json` (Contiene `all_words`, `tags` y `responses`)

**Requerimientos Técnicos:**
1. **Dependencias:** Utiliza `@microsoft/onnxruntime-web` (o `onnxruntime-node`) para cargar el modelo.
2. **Preprocesamiento (Crítico):**
   - Debes implementar una función `tokenize` que pase a minúsculas y separe por palabras.
   - Debes implementar una función `bagOfWords` que replique exactamente la lógica de Python: recorre el array `all_words` del JSON y marca con `1.0` si la palabra (o su raíz) está presente en el input del usuario.
3. **Inferencia:**
   - Carga el modelo ONNX.
   - Convierte el array de Bag of Words en un `ort.Tensor` de tipo `float32` con forma `[1, vocab_size]`.
   - Ejecuta la sesión y obtén el índice con el valor más alto (ArgMax).
4. **Lógica de Memoria:** Implementa un sistema de 'Contexto' básico donde si el tag anterior fue 'recomendaciones' y el usuario menciona 'peso' o 'gordo', el bot responda con la lógica de salud reforzada.
5. **Interfaz:** Crea una función asíncrona simple `chat(inputUsuario)` que devuelva la respuesta final.

**Objetivo:** Entrégame el código en un solo archivo `index.js` listo para probar con Node.js.

---

## 📘 README: Conceptos Clave de NLP en este Chatbot

Este proyecto utiliza técnicas de **Procesamiento de Lenguaje Natural (NLP)** para convertir palabras humanas en números que una Red Neuronal pueda entender. Aquí te explico los pilares del código:

### 1. Tokenización (`tokenize`)
Es el proceso de dividir una cadena de texto (frase) en unidades más pequeñas llamadas **tokens** (palabras).
*   **¿Qué hace?**: Si el usuario escribe "¿Hacen envíos a Cali?", el tokenizador lo convierte en `['hacen', 'envios', 'a', 'cali']`.
*   **Por qué es importante**: La IA no lee oraciones completas, analiza la frecuencia y presencia de palabras individuales.

### 2. Stemming (`stemmer.stem`)
Es una técnica de normalización que reduce las palabras a su **raíz o base** (stem).
*   **¿Qué hace?**:
    *   "Gatos", "Gatito", "Gata" → se reducen a **"gat"**.
    *   "Cocinando", "Cocina", "Cocinero" → se reducen a **"cocin"**.
*   **Por qué es importante**: Ayuda a que el modelo sea más inteligente sin necesidad de entrenarlo con miles de variaciones. Si el bot conoce la raíz "envio", entenderá tanto "envíos" como "enviado".

### 3. Bolsa de Palabras (`Bag of Words`)
Es la forma en que representamos el texto numéricamente.
1.  Creamos un vocabulario maestro con todas las raíces únicas que existen en nuestro dataset (`all_words`).
2.  Para cada frase del usuario, creamos un array de ceros del tamaño del vocabulario.
3.  Ponemos un **1** en la posición de la palabra si esta aparece en la frase.
*   **Ejemplo**: Si nuestro vocabulario es `[gato, casa, jugar]` y el usuario dice "gato jugar", el vector resultante es `[1, 0, 1]`.

### 4. La Red Neuronal (`NeuralNet`)
Es el "cerebro". Recibe el vector de la Bolsa de Palabras y, tras pasar por capas matemáticas (Lineales y ReLU), asigna una puntuación a cada **Tag** (Categoría).
*   **Salida**: El modelo nos da una lista de probabilidades. Nosotros elegimos el **Tag** con la probabilidad más alta.

### 5. ¿Por qué exportamos a ONNX?
PyTorch es una librería de Python muy pesada. **ONNX** es un formato universal "congelado" que permite que este mismo cerebro funcione en un navegador web o un servidor ligero (Vercel) usando JavaScript, sin necesidad de tener Python instalado.
"""