# -*- coding: utf-8 -*-
"""PyTorch_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A0hJxipbydJ03hbqH5ZmfN9aZUZPKNQ1
"""

#!pip install torch
import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import datasets, transforms
from torch.utils.data import DataLoader

class LeNet(nn.Module):
    def __init__(self):
      #Siempre antes de las capas
        super(LeNet, self).__init__()
        #Capas
        self.conv1 = nn.Conv2d(1, 6, kernel_size=5, stride=1, padding=2)
        self.conv2 = nn.Conv2d(6, 16, kernel_size=5, stride=1, padding=0)
        #Reduccion de imagenes
        self.pool = nn.MaxPool2d(kernel_size=2, stride=2)

        self.fc1 = nn.Linear(16 * 5 * 5, 120)  # Resultado : 400(valores), 120(neuronas)
        self.fc2 = nn.Linear(120, 84)           # Resultado : 120(valores) , 84(neuronas)
        self.fc3 = nn.Linear(84, 10)            # Resultado : 84(valores), 10 (Neuronas)
        #nn.Linear es la matriz de pesos

        # Activation
        self.relu = nn.ReLU()
        """Método que define cómo fluyen los datos a través de la red
      ¿Qué hace? Define la operación forward (propagación hacia adelante)"""
    def forward(self, x):
        x = self.conv1(x)           # (batch, 6, 28, 28)
        x = self.relu(x)
        x = self.pool(x)            # (batch, 6, 14, 14)

        x = self.conv2(x)           # (batch, 16, 10, 10)
        x = self.relu(x)
        x = self.pool(x)            # (batch, 16, 5, 5)

        x = x.view(-1, 16 * 5 * 5)  # (batch, 400)
        """Input shape: (64, 16, 5, 5)  # 64 imágenes con 16 mapas de 5×5
           Output shape: (64, 400)      # 64 imágenes flattened"""
        # Fully connected
        x = self.fc1(x)             # (batch, 120)
        x = self.relu(x)

        x = self.fc2(x)             # (batch, 84)
        x = self.relu(x)

        x = self.fc3(x)             # (batch, 10)

        return x

device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(f"Usando: {device}")

# Crear modelo
model = LeNet().to(device) #.to(device) = mueve el modelo a GPU o CPU

# Loss y optimizer
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001) #model.parameters() = todos los pesos a optimizar

transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.1307,), (0.3081,))  # MNIST normalization
])

# Descargar MNIST
train_dataset = datasets.MNIST(root='./data', train=True, download=True, transform=transform)
test_dataset = datasets.MNIST(root='./data', train=False, download=True, transform=transform)

# DataLoaders
train_loader = DataLoader(train_dataset, batch_size=64, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=64, shuffle=False)

print(f"Train samples: {len(train_dataset)}")
print(f"Test samples: {len(test_dataset)}")

num_epochs = 10

for epoch in range(num_epochs):
    model.train()
    total_loss = 0
    correct = 0
    total = 0

    for images, labels in train_loader:
        images, labels = images.to(device), labels.to(device)

        # Forward
        outputs = model(images)
        loss = criterion(outputs, labels)

        # Backward
        optimizer.zero_grad()
        #¿Qué hace? Limpia gradientes anteriores
        #¿Por qué? PyTorch acumula gradientes, necesitas borrarlos cada iteración
        loss.backward()
        optimizer.step()

        # Estadísticas
        total_loss += loss.item()
        _, predicted = torch.max(outputs.data, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()

    accuracy = 100 * correct / total
    avg_loss = total_loss / len(train_loader)

    print(f"Epoch [{epoch+1}/{num_epochs}] Loss: {avg_loss:.4f} Accuracy: {accuracy:.2f}%")

model.eval()
correct = 0
total = 0

with torch.no_grad():
    for images, labels in test_loader:
        images, labels = images.to(device), labels.to(device)
        outputs = model(images)
        _, predicted = torch.max(outputs.data, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()

test_accuracy = 100 * correct / total
print(f"\nTest Accuracy: {test_accuracy:.2f}%")

"""#Representacion grafica"""

import matplotlib.pyplot as plt
import networkx as nx

representacion = nx.DiGraph()

capas = [
    "Input", "Conv1", "ReLU", "Pool1",
    "Conv2", "ReLU", "Pool2", "Flatten",
    "FC1", "ReLU", "FC2", "ReLU", "FC3", "Output"
]

for i in range(len(capas) - 1):
    representacion.add_edge(capas[i], capas[i+1])

plt.figure(figsize=(12, 6))

pos = nx.shell_layout(representacion)

nx.draw(representacion, pos,
        with_labels=True,
        node_color='lightblue',
        node_size=2000,
        font_size=10,
        font_weight='bold',
        arrows=True,
        arrowsize=20)

plt.title("Flujo de Datos en LeNet")
plt.show()