# -*- coding: utf-8 -*-
"""pytorch_4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B1yyYA8Yd5QRl72BtA_Y1xMLl6IgnEQr

#librerias
"""

import torch
import torch.nn as nn
import torch.optim as optim
import torchvision
import torchvision.transforms as transforms
import os
import matplotlib.pyplot as plt

"""#Imagenes

"""

transform = transforms.Compose([transforms.ToTensor(),
                                 transforms.Normalize((0.5,0.5,0.5),(0.5,0.5,0.5))])
trainset = torchvision.datasets.CIFAR10(root='./data',train=True,download=True,transform=transform)
trainloader = torch.utils.data.DataLoader(trainset,batch_size=64,shuffle=True,num_workers=1)

testset = torchvision.datasets.CIFAR10(root='./data',train=False,download=True,transform=transform)
testloader = torch.utils.data.DataLoader(trainset,batch_size=64,shuffle=False,num_workers=1)

dataiter = iter(trainloader)
images,labels = next(dataiter)

imshow = torchvision.utils.make_grid(images)

imshow = imshow.numpy().transpose((1,2,0))

plt.imshow(imshow)
plt.show()

"""#MODELO"""

from typing import Self
class LeNet(nn.Module):
  def __init__(self):
    super(LeNet,self).__init__()
    self.conv1 = nn.Conv2d(3,6,kernel_size=5)
    self.conv2 = nn.Conv2d(6,16,kernel_size=5)
    self.fc1 = nn.Linear(16*5*5,120)
    self.fc2 = nn.Linear(120,84)
    self.fc3 = nn.Linear(84,10)

  def forward(self,x):
    x= torch.tanh(self.conv1(x))
    x= torch.max_pool2d(x,2)
    x= torch.tanh(self.conv2(x))
    x= torch.max_pool2d(x,2)
    x= x.view(-1,16*5*5)
    x= torch.tanh(self.fc1(x))
    x= torch.tanh(self.fc2(x))
    x= self.fc3(x)
    return x
net = LeNet()
net.parameters

criterion= nn.CrossEntropyLoss()
optimizer = optim.SGD(net.parameters(),lr=0.001,momentum=0.9)

from torch.nn.modules import loss
if os.path.isfile("cifar10.pth"):
  net.load_state_dict(torch.load("cifar10.pth"))
loss_history =[]

for epoch in range(50):
  running_loss = 0.0
  for i, data in enumerate(trainloader,0):
    inputs,labels = data

    optimizer.zero_grad()

    outputs = net(inputs)
    loss = criterion(outputs,labels)
    loss.backward()
    optimizer.step()

    running_loss += loss.item()
    if i % 200 == 199:
      print(f"Epoch:{epoch+1}, Batch:{i+1}, Loss:{running_loss/200:.3f}")
      running_loss = 0.0
    loss_history.append(loss.item())
print("Finished Training")

plt.plot(loss_history)
plt.xlabel("batch")
plt.ylabel("lose")
plt.title("loss over training Batches")
plt.show()

correct =0
total =0
with torch.no_grad():
  for data in testloader:
    images,labels = data
    outputs = net(images)
    _,predicted = torch.max(outputs.data,1)
    total += labels.size(0)
    correct += (predicted == labels).sum().item()
print(f"Accurracy of the network on the 10.000 test images: {100*correct/total}%")

"""#REPRESENTACION DE LA RED NEURONAL"""

import networkx as nw
import warnings
warnings.filterwarnings("ignore")

G = nw.DiGraph()


num_muestras = 20
for i in range(num_muestras):
    G.add_node(f"Imagen_{i}")


capas = ["input", "conv1", "pool1", "conv2", "pool2", "fc1", "fc2", "output"]
for capa in capas:
    G.add_node(capa)

for i in range(20):
    G.add_edge(f"Imagen_{i}", "input")

conexiones = [("input", "conv1"), ("conv1", "pool1"), ("pool1", "conv2"),
              ("conv2", "pool2"), ("pool2", "fc1"), ("fc1", "fc2"), ("fc2", "output")]
G.add_edges_from(conexiones)

plt.figure(figsize=(17, 10))
nw.draw(G, with_labels=True, node_color='blue', edge_color='gray', node_size=2000, font_size=10, arrowsize=20)
plt.title("Representación de Flujo: Datos -> Arquitectura LeNet")
plt.show()

