# -*- coding: utf-8 -*-
"""PyTorch_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pClRVXpIhQ6ywurydmmIQ-F3M5i1V1RX
"""

try:
  !pip install torch
except:
  print("torch is already installed")

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
import numpy as np
import json
import random
from sklearn.preprocessing import LabelEncoder
import pickle
import unicodedata

print(" Todos los imports listos")

intenciones = {
    "saludo": [
        "hola", "hey", "buenos días", "buenas noches", "hola cómo estás",
        "¿qué tal?", "saludos", "ey", "hey tú", "hi", "holaaa", "holaaaa",
        "buenos", "buen día", "buenas", "hola que más", "qué onda", "ey qué tal",
        "hola hermano", "hola amigo", "hola tío", "ola", "holi", "presentes", "yo",
        "buenos tardes", "hola que pasa", "qué pasa", "que onda bro"
    ],

    "despedida": [
        "adiós", "hasta luego", "chao", "nos vemos", "que estés bien", "cuídate",
        "bye", "goodbye", "me voy", "hasta pronto", "nos vemos pronto", "cuidate",
        "adios", "vuelvo después", "debo irme", "me tengo que ir", "fue un placer",
        "nos hablamos", "hasta", "chao tío", "me despido", "termino aquí",
        "que estés", "cuidate mucho", "nos vemos luego"
    ],

    "quién_eres": [
        "¿quién eres?", "¿cuál es tu nombre?", "dime tu nombre", "¿cómo te llamas?",
        "¿quién soy?", "cuéntame sobre ti", "¿de dónde eres?", "¿qué eres?",
        "identifícate", "¿cómo te defines?", "cuéntame de ti", "¿tu nombre?",
        "tu identidad", "quién soy yo", "¿cómo te llamas tú?", "¿eres real?",
        "¿eres humano?", "¿qué tipo de entidad eres?", "preséntate",
        "quién es jarvis", "eres jarvis", "tu nombre"
    ],

    "cómo_estás": [
        "¿cómo estás?", "¿qué tal?", "¿cómo te sientes?", "¿y tú?", "¿cómo va?",
        "¿todo bien?", "¿estás bien?", "cuéntame cómo estás", "¿en qué condiciones estás?",
        "¿cómo te va?", "¿cómo andas?", "¿qué tal tu día?", "¿y cómo estás tú?",
        "¿todo ok?", "¿cómo la llevas?", "¿funcionas bien?", "¿estás operativo?",
        "¿en qué estado estás?", "¿cómo estamos?", "¿funcionando?"
    ],

    "ayuda": [
        "ayuda", "¿qué puedes hacer?", "¿cuáles son tus funciones?", "opciones",
        "menú", "¿en qué me ayudas?", "dame opciones", "¿qué servicios ofreces?",
        "dime qué puedes hacer", "necesito ayuda", "ayudame", "¿me ayudas?",
        "¿qué servicios?", "¿cuáles son mis opciones?", "cuéntame tus capacidades",
        "¿qué sabes hacer?", "funciones", "¿tienes herramientas?", "¿qué es lo que sabes?",
        "capabilities", "help", "asistencia"
    ],

    "chiste": [
        "cuéntame un chiste", "hazme reír", "un chiste", "algo gracioso",
        "dime algo divertido", "chiste", "¿sabes chistes?", "cuéntame algo cómico",
        "ríeme", "quiero una broma", "cuéntame algo funny", "algo de humor",
        "hazme gracia", "cuéntame un chiste de programación", "me aburro",
        "diviérteme", "quiero reírme", "broma", "algo para reír",
        "ajajaja", "jajaja", "lol", "haha", "risa"
    ],

    "python": [
        "¿qué es python?", "cuéntame sobre python", "explícame python",
        "¿para qué sirve python?", "python", "lenguaje python", "¿cómo aprendo python?",
        "python para qué", "dime sobre python", "python me interesa", "python es",
        "¿python qué es?", "python útil", "¿debo aprender python?", "¿por qué python?",
        "cuéntame python", "enseñame python", "información sobre python",
        "python tutorial", "como aprender python"
    ],

    "machine_learning": [
        "¿qué es machine learning?", "explícame machine learning", "qué es ml",
        "machine learning", "dime qué es ml", "cuéntame sobre machine learning",
        "¿cómo funciona machine learning?", "machine learning para qué",
        "aprendizaje automático", "inteligencia artificial", "redes neuronales",
        "¿qué es ia?", "deep learning", "neural networks", "machine learning es",
        "cuéntame de ia", "¿cómo aprendo machine learning?", "machine learning aplicaciones",
        "ai", "neural"
    ],

    "sentimientos": [
        "estoy triste", "me siento mal", "no me siento bien", "estoy deprimido",
        "me siento solo", "tengo miedo", "estoy ansioso", "no puedo", "me duele",
        "ayuda me siento mal", "estoy mal", "me siento horrible", "no estoy bien",
        "tengo problemas", "tengo dudas", "estoy preocupado", "estoy estresado",
        "necesito apoyo", "me siento abrumado", "tranquilo", "relax",
        "estoy calmado", "me siento bien", "excelente", "feliz"
    ],

    "confirmación": [
        "sí", "si", "claro", "ok", "vale", "entiendo", "entendido", "perfecto",
        "está bien", "de acuerdo", "dale", "listo", "bueno", "cool", "awesome",
        "ok vale", "entendi", "te entiendo", "comprendido", "con seguridad",
        "claro que sí", "por supuesto"
    ],

    "negación": [
        "no", "nope", "nunca", "jamás", "para nada", "no quiero", "no puedo",
        "no sé", "no se", "ni idea", "ni loco", "de ninguna forma",
        "no gracias", "no gracias", "negado", "rechazar"
    ],

    "gratitud": [
        "gracias", "thank you", "thanks", "muchas gracias", "te agradezco",
        "agradecido", "gracias tío", "gracias hermano", "aprecio", "merci",
        "gracias de verdad", "eres grande", "eres el mejor", "te lo agradezco"
    ],

    "no_entendí": [
        "qué", "no entiendo", "repite", "no capté", "eh", "dijiste qué",
        "no te entendí", "habla más claro", "puedes repetir", "no comprendo",
        "perdón", "disculpa", "¿qué dijiste?", "no escuché", "habla de nuevo",
        "más despacio", "no cacho", "no cachaste"
    ]
}

respuestas = {
    "saludo": [
        "¡Hola! ¿Cómo puedo ayudarte?",
        "¡Bienvenido! ¿Qué necesitas?",
        "Hola! Estoy aquí para asistirte",
        "¡Saludos! ¿En qué puedo ayudarte?",
        "¡Hola! Me alegra verte de nuevo"
    ],

    "despedida": [
        "¡Hasta pronto! Fue un placer hablar contigo",
        "¡Adiós! Cuídate mucho",
        "Nos vemos pronto, ¡que estés bien!",
        "¡Hasta luego! Vuelve cuando necesites",
        "¡Que tengas un excelente día!"
    ],

    "quién_eres": [
        "Soy Jarvis, tu asistente de IA",
        "Me llamo Jarvis, creado para ayudarte",
        "Soy una inteligencia artificial llamada Jarvis",
        "Soy Jarvis, tu chatbot inteligente",
        "Yo soy Jarvis, encantado de conocerte"
    ],

    "cómo_estás": [
        "¡Estoy funcionando perfectamente, gracias por preguntar!",
        "Me siento genial, listo para ayudarte",
        "Estoy excelente, ¿y tú?",
        "Funcionando al 100%, ¿cómo estás tú?",
        "Muy bien, gracias por preguntarme"
    ],

    "ayuda": [
        "Puedo: saludarte, responder preguntas, contarte chistes, explicar Python y Machine Learning, conversar contigo",
        "Soy capaz de: tener conversaciones, ayudarte a aprender, entretenerte, resolver dudas",
        "Mis funciones incluyen: responder preguntas, conversar, enseñar temas técnicos",
        "Puedo ayudarte con: información general, conceptos de programación, conversación casual",
        "Estoy aquí para: apoyarte, resolver dudas y hacer tu día mejor"
    ],

    "chiste": [
        "¿Por qué los programadores prefieren el dark mode? Porque la luz atrae bugs 🐛",
        "Un SQL, un NoSQL y un XML entran a un bar. El bartender: '¿Qué van a beber?' NoSQL: 'No sé, ¿quién es Beber?'",
        "¿Cuántos programadores para cambiar un bombillo? Ninguno, es problema de hardware 💡",
        "¿Qué dijo el programador en el baño? 'Huele a código... ¡Debo limpiar el cache!'",
        "Un byte entra a un bar. Bartender: '¿De dónde vienes?' Byte: 'Del internet, tío' 😄"
    ],

    "python": [
        "Python es versátil y fácil. Se usa para web, IA, análisis de datos y mucho más",
        "Python es perfecto para principiantes por su claridad. Usado por Google, Netflix, Spotify",
        "Es ideal para Machine Learning con librerías como TensorFlow y PyTorch",
        "Con Python haces casi anything: desde webs hasta IA. ¡La mejor opción para empezar!",
        "Python domina IA y análisis de datos. Comunidad ENORME con librerías para todo"
    ],

    "machine_learning": [
        "ML es donde máquinas APRENDEN de datos, sin programarse explícitamente",
        "Permite que modelos mejoren conforme ven más datos. Ej: reconocimiento facial, predicciones",
        "Paradigma donde ENSEÑAS al modelo con datos. El modelo ajusta automáticamente",
        "Usa redes neuronales para patrones. Transforma datos en inteligencia",
        "El futuro: recomendaciones (Netflix), voz (Alexa), autos autónomos, etc"
    ],

    "sentimientos": [
        "Lamento que te sientas así 💙. Recuerda que es temporal. Estoy aquí si necesitas",
        "Entiendo. Pequeños pasos cada día hacen diferencia. ¡Tú puedes! 💪",
        "No estás solo. Busca apoyo en personas que te amen. Esto pasará 🌟",
        "Tu salud mental importa. Si es serio, habla con un profesional",
        "Estoy aquí para escucharte. Cuéntame qué te preocupa"
    ],

    "confirmación": [
        "Perfecto, entendido 👍",
        "Vale, continuamos 💪",
        "Excelente, vamos adelante",
        "De acuerdo, listo",
        "Genial, ¿qué más?"
    ],

    "negación": [
        "Sin problema, entiendo",
        "Está bien, no hay inconveniente",
        "De acuerdo, respetamos tu decisión",
        "Comprendido, sin presión",
        "Okay, como prefieras"
    ],

    "gratitud": [
        "¡De nada! Para eso estamos 😊",
        "Por supuesto, es un placer ayudarte",
        "¡Claro! Estoy aquí para ti",
        "De nada hermano/a, con gusto",
        "¡El placer es mío!"
    ],

    "no_entendí": [
        "Disculpa, no comprendí bien. ¿Puedes decirlo diferente?",
        "Parece que no capté. ¿Puedes repetir?",
        "No estoy seguro. ¿Me lo explicas de otra forma?",
        "Ayúdame: ¿puedes rephrasear tu pregunta?",
        "No entendí bien. ¿Puedes ser más específico?"
    ]
}

print(" Dataset cargado")
print(f"Total intenciones: {len(intenciones)}")
total_frases = sum(len(frases) for frases in intenciones.values())
print(f"Total frases de entrenamiento: {total_frases}")
for intención, frases in intenciones.items():
    print(f"  - {intención}: {len(frases)} ejemplos")

class ChatDataset(Dataset):
    def __init__(self, intenciones):
        self.intenciones = intenciones
        self.todas_las_palabras = []
        self.tags = []
        self.xy = []

        for tag, frases in intenciones.items():
            self.tags.append(tag)
            for frase in frases:
                frase_normalizada = self._normalizar_texto(frase)
                w = self._tokenizar(frase_normalizada)
                self.todas_las_palabras.extend(w)
                self.xy.append((w, tag))

        self.ignorar_palabras = ['?', '!', '.', ',']
        self.todas_las_palabras = sorted(list(set([w for w in self.todas_las_palabras if w not in self.ignorar_palabras])))
        self.vocab = self.todas_las_palabras

        self.label_encoder = LabelEncoder()
        self.labels = self.label_encoder.fit_transform(self.tags)

    def __len__(self):
        return len(self.xy)

    def __getitem__(self, index):
        frase, tag = self.xy[index]
        vector = self._frase_a_vector(frase)
        label = self.label_encoder.transform([tag])[0]
        return torch.tensor(vector, dtype=torch.float32), torch.tensor(label, dtype=torch.long)

    def _tokenizar(self, texto):
        return texto.lower().split()

    def _normalizar_texto(self, texto):
        texto = ''.join(c for c in texto if c.isalnum() or c.isspace() or c in ['?', '!', '.', ','])
        texto = unicodedata.normalize('NFKD', texto).encode('ascii', 'ignore').decode('utf-8', 'ignore')
        return texto.lower()

    def _frase_a_vector(self, tokenized_sentence):
        bag = np.zeros(len(self.vocab), dtype=np.float32)
        for idx, w in enumerate(self.vocab):
            if w in tokenized_sentence:
                bag[idx] = 1
        return bag

class ChatBot(nn.Module):
    """Red neuronal mejorada para clasificar intenciones"""

    def __init__(self, vocab_size, num_intenciones, hidden_size=256):
        super(ChatBot, self).__init__()

        # Capas más profundas
        self.fc1 = nn.Linear(vocab_size, hidden_size)
        self.bn1 = nn.BatchNorm1d(hidden_size)
        self.relu1 = nn.ReLU()
        self.dropout1 = nn.Dropout(0.4)

        self.fc2 = nn.Linear(hidden_size, 128)
        self.bn2 = nn.BatchNorm1d(128)
        self.relu2 = nn.ReLU()
        self.dropout2 = nn.Dropout(0.4)

        self.fc3 = nn.Linear(128, 64)
        self.relu3 = nn.ReLU()
        self.dropout3 = nn.Dropout(0.3)

        self.fc4 = nn.Linear(64, num_intenciones)

    def forward(self, x):
        x = self.fc1(x)
        x = self.bn1(x)
        x = self.relu1(x)
        x = self.dropout1(x)

        x = self.fc2(x)
        x = self.bn2(x)
        x = self.relu2(x)
        x = self.dropout2(x)

        x = self.fc3(x)
        x = self.relu3(x)
        x = self.dropout3(x)

        x = self.fc4(x)
        return x

# Recrear dataset (importante)
dataset = ChatDataset(intenciones)

# Crear modelo NUEVO
vocab_size = len(dataset.vocab)
num_intenciones = len(dataset.label_encoder.classes_)

device = 'cuda' if torch.cuda.is_available() else 'cpu'
model = ChatBot(vocab_size, num_intenciones, hidden_size=256).to(device)

train_loader = DataLoader(dataset, batch_size=4, shuffle=True, drop_last=True)  # Batch más pequeño

print(f" Modelo creado")
print(f"  - Vocabulary size: {vocab_size}")
print(f"  - Intenciones: {num_intenciones}")
print(f"  - Clases: {list(dataset.label_encoder.classes_)}")
print(f"  - Device: {device}")

# Loss y optimizer
criterion = nn.CrossEntropyLoss()
optimizer = optim.AdamW(model.parameters(), lr=0.002, weight_decay=0.0001)
scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=50, gamma=0.5)

# Entrenamiento
num_epochs = 80
best_loss = float('inf')
best_accuracy = 0

print("Entrenamiento (80 épocas)...\n")

for epoch in range(num_epochs):
    model.train()
    total_loss = 0
    correct = 0
    total = 0

    for X, y in train_loader:
        X, y = X.to(device), y.to(device)

        # Forward
        outputs = model(X)
        loss = criterion(outputs, y)

        # Backward
        optimizer.zero_grad()
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
        optimizer.step()

        # Estadísticas
        total_loss += loss.item()
        _, predicted = torch.max(outputs, 1)
        correct += (predicted == y).sum().item()
        total += y.size(0)

    scheduler.step()

    accuracy = 100 * correct / total
    avg_loss = total_loss / len(train_loader)

    # Guardar mejor modelo
    if avg_loss < best_loss or accuracy > best_accuracy:
        best_loss = avg_loss
        best_accuracy = accuracy
        torch.save(model.state_dict(), 'chatbot_model_mejorado.pth')

    # Imprimir cada 30 épocas
    if (epoch + 1) % 30 == 0:
        print(f"Epoch [{epoch+1}/{num_epochs}] Loss: {avg_loss:.4f} Accuracy: {accuracy:.2f}%")

print(f"\n Entrenamiento completado")
print(f"Mejor loss: {best_loss:.4f}")
print(f"Mejor accuracy: {best_accuracy:.2f}%")
print(f"Modelo guardado como 'chatbot_modelo_mejorado.pth'")

def obtener_respuesta(texto_usuario, model, dataset, respuestas, threshold=0.35):


    model.eval()

    # Convertir texto a vector
    vector = dataset._frase_a_vector(texto_usuario)
    X = torch.tensor(vector, dtype=torch.float32).unsqueeze(0).to(device)

    # Predecir
    with torch.no_grad():
        outputs = model(X)
        probabilities = torch.softmax(outputs, dim=1)
        confianza, idx = torch.max(probabilities, 1)

    confianza = confianza.item()
    idx = idx.item()

    # Decodificar intención
    intención = dataset.label_encoder.inverse_transform([idx])[0]

    # Threshold adaptativo
    if confianza < threshold:
        intención = "no_entendí"

    # Seleccionar respuesta aleatoria
    respuesta = random.choice(respuestas[intención])

    return respuesta, confianza, intención

print(" Función de predicción mejorada lista")

def chatbot():
    """Chatbot mejorado y final"""

    print("\n" + "="*70)
    print(" Modelo - CHATBOT IA ")
    print("="*70)
    print("\n Escribe tus mensajes. Escribe 'salir' para terminar\n")
    print("-"*70 + "\n")

    while True:
        usuario = input("Tú: ").strip()

        if usuario.lower() == 'salir':
            print("\nModelo: ¡Hasta luego! Que estés bien \n")
            break

        if not usuario:
            continue

        respuesta, confianza, intención = obtener_respuesta(
            usuario,
            model,
            dataset,
            respuestas,
            threshold=0.35
        )

        print(f"\nModelo: {respuesta}")
        print(f"[Intención: {intención} | Confianza: {confianza:.2%}]\n")
        print("-"*70 + "\n")

chatbot()

"""## Mejoras a Futuro

Para optimizar el rendimiento y la precisión del chatbot, se sugieren las siguientes acciones:

1.  **Ajuste de Pesos y Arquitectura:** Refinar los hiperparámetros (learning rate, hidden size) y la estructura de la red neuronal para evitar el sobreajuste o infraajuste.
2.  **Enriquecimiento del Dataset:** Agregar más variaciones de frases para las intenciones que presentan baja confianza (como en los errores de ortografía).
3.  **Embeddings Avanzados:** Utilizar representaciones de palabras más complejas (como Word2Vec o FastText) en lugar de bag-of-words para captar mejor el contexto semántico.
4.  **Balanceo de Clases:** Asegurar que todas las intenciones tengan un número similar de ejemplos de entrenamiento para evitar sesgos hacia las categorías más frecuentes.
"""