# -*- coding: utf-8 -*-
"""Pytorch_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VEAUPxnpxK6qZ4jepP5MBCrCqhS7cRE1

#Liberias
"""

import torch as tc
import numpy as np

"""#Codigo"""

x = tc.rand(4,3)
print (x)

print(tc.tensor(np.array([[1,2],[3,4]])))
print(tc.tensor([True,False]))
print(tc.tensor((1,2,3,4,5)))
print(tc.tensor([i for i in range(10)]))

print(tc.FloatTensor(2,3).type())
print(tc.DoubleTensor(2,3).type())
print(tc.HalfTensor(2,3).type())
print(tc.ByteTensor(2,3).type())
print(tc.CharTensor(2,3).type())
print(tc.ShortTensor(2,3).type())
print(tc.IntTensor(2,3).type())
print(tc.LongTensor(2,3).type())

"""### Descripción y Utilidad de los Tipos de Tensores

| Tipo de Tensor | Clase de PyTorch | Descripción | Utilidad Principal |
| :--- | :--- | :--- | :--- |
| **Float** | `tc.FloatTensor` | Punto flotante de 32 bits. | Es el estándar para pesos de redes neuronales y cálculos de precisión simple. |
| **Double** | `tc.DoubleTensor` | Punto flotante de 64 bits. | Se usa cuando se requiere una precisión matemática extrema (cálculos científicos). |
| **Half** | `tc.HalfTensor` | Punto flotante de 16 bits. | Ideal para entrenamiento de 'precisión mixta' para ahorrar memoria y ganar velocidad en GPUs modernas. |
| **Byte** | `tc.ByteTensor` | Enteros de 8 bits sin signo (0 a 255). | Comúnmente usado para máscaras booleanas (aunque ahora existe `BoolTensor`) o datos de imágenes. |
| **Char** | `tc.CharTensor` | Enteros de 8 bits con signo (-128 a 127). | Útil para almacenamiento de datos muy pequeños y cuantización. |
| **Short** | `tc.ShortTensor` | Enteros de 16 bits con signo. | Ahorro de memoria cuando los valores no superan los +/- 32,767. |
| **Int** | `tc.IntTensor` | Enteros de 32 bits con signo. | Usado para índices o conteos que no requieren el rango de 64 bits. |
| **Long** | `tc.LongTensor` | Enteros de 64 bits con signo. | **Fundamental** para etiquetas de clasificación (targets) e índices de búsqueda (embeddings). |
"""

x =tc.zeros(4,3,dtype=tc.long)
print(x)
x= tc.ones(4,3,dtype=tc.long)
print(x)
x=x.new_ones(4,3,dtype=tc.double)
print(x)
x=tc.randn_like(x,dtype=tc.float)
print(x)

"""### Métodos de Creación y Transformación de Tensores

| Método | Descripción | Utilidad Principal |
| :--- | :--- | :--- |
| `tc.zeros(shape)` | Crea un tensor lleno de ceros con la forma especificada. | Inicialización de estados, acumuladores o padding. |
| `tc.ones(shape)` | Crea un tensor lleno de unos con la forma especificada. | Inicialización de constantes o máscaras unitarias. |
| `tensor.new_ones(shape)` | Crea un nuevo tensor de unos **reutilizando atributos** (como el dispositivo) del tensor original. | Mantener la consistencia del dispositivo (CPU/GPU) al crear nuevos datos. |
| `tc.randn_like(tensor)` | Crea un tensor con valores aleatorios (distribución normal) con la **misma forma** que el tensor dado. | Generación de ruido o inicialización aleatoria basada en un tensor de referencia. |
"""

x =tc.Tensor(np.array([[1,2],[3,4]]))
print(x.shape)
print(x.size())
print(x.dim())
print(x.device)
print(x.dtype)

device = "cuda" if tc.cuda.is_available() else "cpu"

x =tc.Tensor(np.array([[1,2],[3,4]]))
print(x.reshape(4,1))
x= x.unsqueeze(2)
print(x.shape)
x=x.squeeze(2)
print(x.shape)

print(x.flatten())
x = x.to(device)
print(f"Tensor movido a: {x.device}")

"""### Manipulación de Dimensiones y Dispositivos

| Método | Descripción | Utilidad Principal |
| :--- | :--- | :--- |
| `reshape(shape)` | Cambia la forma del tensor sin cambiar sus datos. | Adaptar la salida de una capa a la entrada de otra (ej. de Conv a Linear). |
| `unsqueeze(dim)` | Añade una dimensión extra de tamaño 1 en la posición indicada. | Simular un 'batch size' de 1 o añadir canales a una imagen. |
| `squeeze(dim)` | Elimina dimensiones de tamaño 1. | Limpiar dimensiones innecesarias tras una operación. |
| `flatten()` | Aplana el tensor a una sola dimensión (vector). | Preparar datos para capas de clasificación finales. |
| `to(device)` | Mueve el tensor al dispositivo especificado (CPU o GPU). | **Crucial** para acelerar cálculos usando la tarjeta gráfica (CUDA). |
"""